Repository WeAreRoommies/Roomie-Android, pull requests merged in 2025-06, with the labels that each got.

#136 [Feature/#134] 온보딩 구현
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/onboarding/OnboardingRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/onboarding/component/OnboardingPagerItem.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/onboarding/navigation/navigateToOnboarding.kt
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉, 🎨 ui 🎨

#135 [feature/#123] kakao social login 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wearerommies/roomie/Roomie.kt
  app/src/main/java/com/wearerommies/roomie/data/datalocal/datasource/TokenDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/datasource/AuthDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/datasource/UserDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/datasource/interceptor/AuthInterceptor.kt
  app/src/main/java/com/wearerommies/roomie/data/di/DataSourceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/NetworkModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/RepositoryModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/ServiceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/SharedPreferencesModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/qualifier/Qualifier.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/request/RequestSocialLoginDto.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseHomeDto.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseReissueTokenDto.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseTokenDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/TokenRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/AuthService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/HomeDataEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/ReissueTokenEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/SocialLoginEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/SocialSignUpEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/TokenEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/AuthRepository.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/TokenRepository.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/UserRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/login/LoginRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/login/LoginSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/login/LoginState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/login/navigation/LoginNavigation.kt
  app/src/main/res/drawable/ic_roomie_logo.xml
  app/src/main/res/drawable/img_kakao_login.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#138 [feature/#137] 온보딩에 자동 로그인 적용
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainActivity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/login/LoginRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/SplashRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/SplashSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/SplashState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/SplashViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/navigation/navigateToSplash.kt
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉

#146 [chore/#145] naver map 업데이트
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🪛 fix 🪛
