Repository WeAreRoommies/Roomie-Android, pull requests merged in 2025-01, with the labels that each got.

#1 setting: 깃허브 세팅
  .github/ISSUE_TEMPLATE/issue_rommie.md
  .github/pull_request_template.md
  .gitignore
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🔧 setting 🔧

#3 [setting/#2] android 세팅
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/wearerommies/roomie/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wearerommies/roomie/Roomie.kt
  app/src/main/java/com/wearerommies/roomie/data/datasource/ReqresDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/di/DataSourceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/NetworkModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/RepositoryModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/ServiceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseReqresDto.kt
  app/src/main/java/com/wearerommies/roomie/data/mapper/todomain/ResponseReqresDtoMapper.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/ReqresRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/ReqresService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/ReqresEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/ReqresRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Context.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Modifier.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/PriceFormatter.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/UiState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/dummy/ReqresRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/dummy/ReqresSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/dummy/ReqresState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/dummy/ReqresViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainActivity.kt
  app/src/main/java/com/wearerommies/roomie/ui/theme/Color.kt
  app/src/main/java/com/wearerommies/roomie/ui/theme/Theme.kt
  app/src/main/java/com/wearerommies/roomie/ui/theme/Type.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/wearerommies/roomie/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🔧 setting 🔧

#9 [setting/#6] 아이콘 세팅
  app/src/main/res/drawable/ic_arrow_down_filled_black_16px.xml
  app/src/main/res/drawable/ic_arrow_down_line_black_16px.xml
  app/src/main/res/drawable/ic_arrow_down_line_black_24px.xml
  app/src/main/res/drawable/ic_arrow_down_line_gray_24px.xml
  app/src/main/res/drawable/ic_arrow_down_line_white_16px.xml
  app/src/main/res/drawable/ic_arrow_down_line_white_24px.xml
  app/src/main/res/drawable/ic_arrow_left_line_black_16px.xml
  app/src/main/res/drawable/ic_arrow_left_line_black_24px.xml
  app/src/main/res/drawable/ic_arrow_left_line_white_16px.xml
  app/src/main/res/drawable/ic_arrow_left_line_white_24px.xml
  app/src/main/res/drawable/ic_arrow_right_line_black_16px.xml
  app/src/main/res/drawable/ic_arrow_right_line_black_24px.xml
  app/src/main/res/drawable/ic_arrow_right_line_lightgray_24px.xml
  app/src/main/res/drawable/ic_arrow_right_line_white_16px.xml
  app/src/main/res/drawable/ic_arrow_right_line_white_24px.xml
  app/src/main/res/drawable/ic_arrow_up_filled_black_16px.xml
  app/src/main/res/drawable/ic_arrow_up_line_black_16px.xml
  app/src/main/res/drawable/ic_arrow_up_line_black_24px.xml
  app/src/main/res/drawable/ic_arrow_up_line_gray_24px.xml
  app/src/main/res/drawable/ic_arrow_up_line_white_16px.xml
  app/src/main/res/drawable/ic_arrow_up_line_white_24px.xml
  app/src/main/res/drawable/ic_calender_24px.xml
  app/src/main/res/drawable/ic_check_priamrycolor_20px.xml
  app/src/main/res/drawable/ic_delete_20px.xml
  app/src/main/res/drawable/ic_detail__calendar_20px.xml
  app/src/main/res/drawable/ic_detail_gender_20px.xml
  app/src/main/res/drawable/ic_detail_location_20px.xml
  app/src/main/res/drawable/ic_detail_room_20px.xml
  app/src/main/res/drawable/ic_detail_totalpeople_20px.xml
  app/src/main/res/drawable/ic_filter_line_gray_24px.xml
  app/src/main/res/drawable/ic_heart_24px_active.xml
  app/src/main/res/drawable/ic_heart_24px_normal.xml
  app/src/main/res/drawable/ic_heart_filled_white_24px.xml
  app/src/main/res/drawable/ic_heart_line_black_24px.xml
  app/src/main/res/drawable/ic_heart_line_primary_24px.xml
  app/src/main/res/drawable/ic_heart_linewithfill_white_24px.xml
  app/src/main/res/drawable/ic_home_line_black_24px.xml
  app/src/main/res/drawable/ic_home_line_primary_24px.xml
  app/src/main/res/drawable/ic_house_white_12px.xml
  app/src/main/res/drawable/ic_image_24px.xml
  app/src/main/res/drawable/ic_inquire_24px.xml
  app/src/main/res/drawable/ic_map2_line_black_24px.xml
  app/src/main/res/drawable/ic_map2_line_primary_24px.xml
  app/src/main/res/drawable/ic_map_fillter_20px.xml
  app/src/main/res/drawable/ic_map_line_black_16px.xml
  app/src/main/res/drawable/ic_map_line_black_24px.xml
  app/src/main/res/drawable/ic_map_line_primary_24px.xml
  app/src/main/res/drawable/ic_map_pin_active.png
  app/src/main/res/drawable/ic_map_pin_normal.png
  app/src/main/res/drawable/ic_search_24px.xml
  app/src/main/res/drawable/ic_search_line_black_24px.xml
  app/src/main/res/drawable/ic_search_line_gray_24px.xml
  app/src/main/res/drawable/ic_search_line_primary_24px.xml
  app/src/main/res/drawable/ic_user_line_black_24px.xml
  app/src/main/res/drawable/ic_user_line_primary_24px.xml
  app/src/main/res/drawable/ic_warning_14px.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🔧 setting 🔧

#7 [setting/#5] 폰트, 컬러, 테마 세팅
  app/src/main/java/com/wearerommies/roomie/ui/theme/Color.kt
  app/src/main/java/com/wearerommies/roomie/ui/theme/Theme.kt
  app/src/main/java/com/wearerommies/roomie/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🔧 setting 🔧

#16 [feature/#15] 리뷰어 자동 설정
  .github/CODEOWNERS
  .github/workflows/auto_assign.yml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🔧 setting 🔧

#21 [feature/#20] modifier 확장 함수 추가
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Modifier.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#26 [feature/#22] 스낵바, 버튼 공통 컴포넌트 제작
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieSnackBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Modifier.kt
  app/src/main/java/com/wearerommies/roomie/ui/theme/Color.kt
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉

#23 [feature/#19] date picker component 구현
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieDatePickerField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/DatePickerFieldType.kt
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉

#25 [feature/#18] 공통 컴포넌트 제작
  app/src/main/java/com/wearerommies/roomie/domain/entity/RoomCardEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieChip.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieFooter.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieNavigateButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieRoomAsset.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieRoomCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieTopBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/MainBottomBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/NavigateButtonType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/res/drawable/ic_heart_line_black_24px.xml
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉, 🎨 ui 🎨

#17 [feature/#14] 지도뷰 컴포넌트 제작
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Modifier.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/ShadowTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapTopBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MarkerDetailCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/component/SearchTextField.kt
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉

#27 [feature/#24] text field 컴포넌트 제작
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RommieTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieTextFieldWithTitle.kt
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉, 🎨 ui 🎨

#32 [feature/#30] home뷰 component 제작
  app/src/main/java/com/wearerommies/roomie/presentation/type/HomeMoodCardType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/component/HomeMoodCard.kt
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉, 🎨 ui 🎨

#33 [feature/#19] date picker 관련 컴포넌트 제작
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieDatePicker.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieDatePickerField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/DateFormatter.kt
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉, 🎨 ui 🎨

#31 [feature/#30] my뷰 component 제작
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/component/MyButtonWithHelperText.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/component/MyProfileCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/component/MyTitleBox.kt
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉, 🎨 ui 🎨

#40 [feature/#39] my UI 뷰 구현
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/MyType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/component/MyButtonWithHelperText.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/component/MyTitleBox.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/navigation/MyNavigation.kt
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉, 🎨 ui 🎨

#38 [feature/#34] home 뷰 구현
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieRoomCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieTopBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Modifier.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainScreen.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/MainBottomBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/NavigateButtonType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/component/HomeMoodCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/res/drawable/img_home_character.png
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉, 🎨 ui 🎨

#41 [feature/#37] 검색 뷰 구현
  app/src/main/java/com/wearerommies/roomie/domain/entity/SearchResultEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieEmptyView.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/EmptyViewType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/MapRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapTopBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/navigation/MapNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/component/SearchResultCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/navigation/SearchNavigation.kt
  app/src/main/res/drawable/img_crying.png
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉, 🎨 ui 🎨

#48 [feature/#45] navigation 세팅
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/BookmarkNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/DetailNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/MoodNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/navigation/FilterNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/navigation/TourNavigation.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#52 [feature/#49] 상세 내부 이미지 및 투어 컴포넌트 구현
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RommieTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieNavigateButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Modifier.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailContentHeader.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailImagePager.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailInnerFacilityCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailInnerImageButton.kt
  app/src/main/res/values/strings.xml
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉, 🎨 ui 🎨

#54 [feature/#34] HomeMoodCard 이미지 추가
  app/src/main/java/com/wearerommies/roomie/presentation/type/HomeMoodCardType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/component/HomeMoodCard.kt
  app/src/main/res/drawable/img_home_active.png
  app/src/main/res/drawable/img_home_calm.png
  app/src/main/res/drawable/img_home_clean.png
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉, 🎨 ui 🎨

#56 [feature/#53] 투어 신청 화면 구현
  app/src/main/java/com/wearerommies/roomie/domain/entity/TourEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RommieTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieTextFieldWithTitle.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/DatePickerFieldType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/GenderType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourCompletedStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourFirstStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourSecondStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourThirdStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourViewModel.kt
  app/src/main/res/drawable/img_tour_apply_complete.png
  app/src/main/res/values/strings.xml
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉, 🎨 ui 🎨

#58 [fix/#55] 홈/찜/분위기/마이페이지 뷰 자체 qa
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieNavigateButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieRoomCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/MyType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/component/HomeMoodCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/component/MyProfileCard.kt
  app/src/main/res/drawable/img_profile.png
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🪛 fix 🪛, 🎨 ui 🎨

#67 [feature/#59] 홈 api 연결
  app/src/main/java/com/wearerommies/roomie/data/datasource/HomeDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/di/DataSourceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/RepositoryModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/ServiceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/BaseResponse.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseHomeDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/HomeService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/HomeDataEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/RoomCardEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/HomeRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#70 [feature/#60] 분위기 별 리스트 api 연결
  app/src/main/java/com/wearerommies/roomie/data/datasource/HouseDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/di/DataSourceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/RepositoryModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/ServiceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseMoodDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/HouseRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/HouseService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/MoodCardEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/HouseRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/component/HomeMoodCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#66 [feature/#57] 상세보기 이미지 집,방 뷰 구현
  app/src/main/java/com/wearerommies/roomie/domain/entity/DetailHouseEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/DetailHouseImageEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/DetailRoomEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailImagePager.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailInnerFacilityCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/house/DetailHouseRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/house/DetailHouseSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/house/DetailHouseState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/house/DetailHouseViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/navigation/DetailNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/room/DetailRoomRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/room/DetailRoomSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/room/DetailRoomState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/room/DetailRoomViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉, 🎨 ui 🎨

#64 [feature/#43] filter UI
  app/src/main/java/com/wearerommies/roomie/domain/entity/FilterEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieDatePicker.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailRoomInfoTexts.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/ColumnWithTitle.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/FilterBottomBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/FilterChip.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/FilterTab.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/FilterTabRow.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/FilterTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/navigation/FilterNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/screen/ContractTypeScreen.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/screen/RentScreen.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/screen/RoomTypeScreen.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapShadowTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapTopBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/navigation/MapNavigation.kt
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉, 🎨 ui 🎨

#72 [feature/#69] splash 화면 구현
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainActivity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/navigation/navigateToSplash.kt
  app/src/main/res/drawable/ic_splash_character_white.xml
  app/src/main/res/drawable/ic_splash_logo_white.xml
  app/src/main/res/values/themes.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉, 🎨 ui 🎨

#74 [feature/#61] 사용자의 찜 리스트 api 연결
  app/src/main/java/com/wearerommies/roomie/data/datasource/HouseDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseBookmarkListDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/HouseRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/HouseService.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/HouseRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/component/BookmarkEmptyView.kt
  app/src/main/res/drawable/img_sweating.png
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#77 [fix/#76] viewmodel 수정
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyViewModel.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🪛 fix 🪛

#79 [fix/#78] uistate 제거
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/MyViewModel.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🪛 fix 🪛

#80 [feature/#73] search api 연결
  app/src/main/java/com/wearerommies/roomie/data/datasource/MapDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/di/DataSourceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/RepositoryModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/ServiceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseSearchDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/MapService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/SearchResultEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/MapRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapShadowTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapTopBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/component/SearchTextField.kt
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉

#82 [feature/#75] 상세 화면 구현
  app/src/main/java/com/wearerommies/roomie/domain/entity/DetailEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailBottomSheet.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailBottomSheetTourOptionButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailContentHeader.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailMainImageWithBackButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailMoodCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailRoomMateCard.kt
  app/src/main/res/values/strings.xml
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉, 🎨 ui 🎨

#84 [feature/#63] 하우스 찜 api 연결
  app/src/main/java/com/wearerommies/roomie/data/datasource/HouseDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/HouseRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/HouseService.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/HouseRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodViewModel.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#86 [feature/#83] 상세보기 뷰 api 연결
  app/src/main/java/com/wearerommies/roomie/data/datasource/HouseDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseDetailDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/HouseRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/HouseService.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/HouseRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailInnerFacilityCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/navigation/DetailNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/navigation/HomeNavigation.kt
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉

#91 [feature/#85] webview 구현
  app/build.gradle.kts
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieWebView.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/webview/WebViewRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/webview/navigation/WebViewNavigation.kt
  gradle/libs.versions.toml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉, 🎨 ui 🎨

#94 [feature/#92] 상세 매물 navigation 연결
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/navigation/BookmarkNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/navigation/MoodNavigation.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#96 [fix/#95] 하우스 찜 response object 추가
  app/src/main/java/com/wearerommies/roomie/data/datasource/HouseDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseBookmarkDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/HouseRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/HouseService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/BookmarkEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/HouseRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodViewModel.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🪛 fix 🪛

#98 [feature/#89] 필터 api 적용
  app/src/main/java/com/wearerommies/roomie/domain/entity/FilterEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/SearchResultEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/MainTabType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/navigation/FilterNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/screen/ContractTypeScreen.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/MapRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/MapSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/MapState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/MapViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapBottomSheet.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapTopBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/navigation/MapNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/navigation/SearchNavigation.kt
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🎉feature 🎉

#105 [feature/#93] 투어 신청 api 연결
  app/src/main/java/com/wearerommies/roomie/data/datasource/RoomDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/di/DataSourceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/RepositoryModule.kt
  app/src/main/java/com/wearerommies/roomie/data/di/ServiceModule.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/request/RequestTourApplyDto.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseTourApplyDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/RoomRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/RoomService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/TourEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/RoomRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/DateFormatter.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailBottomSheet.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailBottomSheetTourOptionButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/navigation/DetailNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/TourViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/completed/TourCompletedSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/completed/TourCompletedStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/completed/TourCompletedStepViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/first/TourFirstSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/first/TourFirstState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/first/TourFirstStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/first/TourFirstViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/navigation/TourNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/third/TourThirdSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/third/TourThirdState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/third/TourThirdStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/third/TourThirdViewModel.kt
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉

#107 [feature/#101] 네비게이션 애니메이션 수정
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/MainBottomBar.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodRoute.kt
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🪛 fix 🪛

#108 [feature/#102] 상세 매물 페이지 기능 연결
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseDetailDto.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/DetailEntity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieWebView.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/navigation/DetailNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/webview/WebViewRoute.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#111 [fix/#106] 투어뷰 수정
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieDatePicker.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieTextFieldWithTitle.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/RegexConstants.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/DatePickerFieldType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondStepRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🪛 fix 🪛

#112 [fix/#110] 수현 자체 QA
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseBookmarkListDto.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/MapViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mood/MoodViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🪛 fix 🪛

#115 [fix/#113] 예인 자체 qa 반영
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailImagePager.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/house/DetailHouseRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/tour/second/TourSecondState.kt
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🪛 fix 🪛

#114 [feature/#109] 혜음 자체 QA 진행
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RommieTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieDatePicker.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/extension/Modifier.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/route/Route.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailBottomIconButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailBottomSheet.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/component/DetailRoomInfoCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/house/DetailHouseRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/FilterViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/FilterChip.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/component/FilterTextField.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/filter/screen/RentScreen.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/component/HomeMoodCard.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/MapRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/map/component/MapBottomSheet.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/drawable/ic_splash_character_white.xml
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/drawable/ic_splash_logo_white.xml
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🪛 fix 🪛

#117 [fix/#116] 시연 중 발견한 이슈 해결
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/res/values/strings.xml
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🪛 fix 🪛

#119 [fix/#118] 2차 자체 QA
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainActivity.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
Labels: ( ˶’ᵕ’˶ ) 혜음 ( ˶’ᵕ’˶ ), 🪛 fix 🪛
