Repository WeAreRoommies/Roomie-Android, pull requests merged in 2025-07, with the labels that each got.

#151 [feature/#148] 로그아웃, 회원탈퇴 구현
  app/src/main/java/com/wearerommies/roomie/data/datasource/AuthDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/AuthService.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/AuthRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieButton.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieDialog.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/component/RoomieTwoButtonDialog.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/GenderFormatter.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/PhoneNumberFormatter.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/UserConstants.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/MainNavigator.kt
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/TwoButtonDialogType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/myaccount/MyAccountRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/myaccount/MyAccountSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/myaccount/MyAccountState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/myaccount/MyAccountViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/myaccount/navigation/MyAccountNavigation.kt
  app/src/main/res/values/strings.xml
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#152 [feature/#144] 관심지역 설정 바텀시트 및 api
  app/src/main/java/com/wearerommies/roomie/data/datasource/UserDataSource.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/request/RequestLocationDto.kt
  app/src/main/java/com/wearerommies/roomie/data/dto/response/ResponseLocationDto.kt
  app/src/main/java/com/wearerommies/roomie/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/wearerommies/roomie/data/service/UserService.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/LocationEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/entity/SearchResultEntity.kt
  app/src/main/java/com/wearerommies/roomie/domain/repository/UserRepository.kt
  app/src/main/java/com/wearerommies/roomie/presentation/core/util/UiState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/bookmark/BookMarkRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeState.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/component/LocationBottomSheet.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/SearchRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/search/component/SearchResultCard.kt
  app/src/main/res/drawable/img_search_place.png
  app/src/main/res/values/strings.xml
Labels: ᑦ(⁎◕ ˕ ◕)ᐣ 예인 ᑦ(⁎◕ ˕ ◕)ᐣ, 🎉feature 🎉

#154 [feature/#153] 웹뷰 연결
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/type/MyType.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/home/HomeRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/my/MyRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/my/MySideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/my/MyViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/my/navigation/MyNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/webview/WebViewRoute.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🎉feature 🎉

#156 [fix/#155] 카카오톡 채널 연결 오류 수정
  app/src/main/java/com/wearerommies/roomie/presentation/navigator/component/RoomieNavHost.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailSideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/detail/navigation/DetailNavigation.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/my/MyRoute.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/my/MySideEffect.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/mypage/my/MyViewModel.kt
  app/src/main/java/com/wearerommies/roomie/presentation/ui/webview/WebViewRoute.kt
Labels: ˶•⩊•˶ 수현 ˶•⩊•˶, 🪛 fix 🪛
